### ISSUE TITLE
Use with MapBox?

### ISSUE THREAD

**Issue by sirvon** [arsy1995/GoogleMapsRippleEffect#2]
Is this library/functionality interop with Mapbox's SDK?

thanks for your work!

**Comment by aarsy** [comment]
No, currently i'm using it only with google maps API.

**Comment by sirvon** [comment]
btw it's native in MapBox...

[mapbox-gl-native/issues/5985](https://github.com/mapbox/mapbox-gl-native/issues/5985)

**Comment by aarsy** [comment]
Sorry sirvon, Since i have not used Mapbox so i don't have any idea about how it works. May be i can help you after few days after knowing how Mapbox works
