### ISSUE TITLE
How to achieve a blue dot ? 

### ISSUE THREAD

**Issue by moheny** [arsy1995/GoogleMapsRippleEffect#3]
i'm trying to achieve the same result as you have on your first image.
the blue dot with transparent radius effect. but for some reason all i see is huge dot and it's not small at all. I have tried to customized it but still it's big as hell.
is it possible to achieve the same result as your first image ? i was sure it was the default settings.
Thank you so much for this great library.

**Comment by aarsy** [comment]
Are you using Fused Location API or Location Manager??
You can view this stack-overflow post for your issue.
http://stackoverflow.com/questions/30253123/blue-dot-and-circle-is-not-shown-on-mylocation-using-android-fused-location-api

**Comment by VasuNIPL** [comment]
Het @moheny have you find the solution?I have face the same issue and need help

**Comment by moheny** [comment]
@VasuNIPL I found the solution but it was 2 years ago, I have no idea where the project is - sorry I cannot help.
