### ISSUE TITLE
canot compile library

### ISSUE THREAD

**Issue by enggazzar** [arsy1995/GoogleMapsRippleEffect#4]
Warning:Module 'com.github.aarsy.googlemapsanimations:googlemapsanimations:1.0.3' depends on one or more Android Libraries but is a jar

**Comment by aarsy** [comment]
I have written there on readme. Dependency distribution isn't working for now due to some issues. You can fork the project or download it manually for now

**Comment by aarsy** [comment]
I have written there on readme. Dependency distribution isn't working for now due to some issues. You can fork the project or download it manually for now

**Comment by enggazzar** [comment]
thanks
