### ISSUE TITLE
drawable.BitmapDrawable cannot be cast to android.graphics.drawable.GradientDrawable

### ISSUE THREAD

**Issue by iceberg1369** [arsy1995/GoogleMapsRippleEffect#6]
hi there
I get following error

    java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.GradientDrawable
    at com.arsy.maps_library.MapRipple.<init>(MapRipple.java:67)

**Comment by aarsy** [comment]
Hi iceberg1369, This is a naming bug. Please check whether you have any drawable in you project with name "background". Please refactor->rename the one in your project. This bug is arising because I have been also using same name drawable in my library

**Comment by iceberg1369** [comment]
yes, you were right. it's good idea that library resources should have prefix in the name.
but I've got new error now:

    java.lang.OutOfMemoryError: Failed to allocate a 67108876 byte allocation with 4194208 free bytes and 16MB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)

**Comment by aarsy** [comment]
Hehe.... You can refer here https://github.com/aarsy/GoogleMapsAnimations/issues/5
I shall solve both the bugs in some days. Up to then please do it yourself.
